# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:        9e6b0c38c01db1462532cbd0017e04e4389bf35108b29d53aa8f037fb1d066f144e921075f1c45a497a25edcb71299a3620eeb1d4bcad5541437f51c416355d6
  twilio_account_sid:     <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:      <%= ENV["TWILIO_AUTH_TOKEN"] %>
  sendgrid_username:      <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password:      <%= ENV["SENDGRID_PASSWORD"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key:      <%= ENV['STRIPE_SECRET_KEY'] %>

test:
  secret_key_base: b5b9ba99e07fa1fd11b2c7f84a3a0812eb6d89531a51039e22defe9b5d2db3b11e5e077d31eca7582d21bda37d7ffb37816a9e7b522c96f5c51f9d5248cb09a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid:     <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:      <%= ENV["TWILIO_AUTH_TOKEN"] %>
  sendgrid_username:      <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password:      <%= ENV["SENDGRID_PASSWORD"] %>
  odh_db_host:            <%= ENV['ODH_DB_HOST'] %>
  odh_db_port:            <%= ENV['ODH_DB_PORT'] %>
  odh_db_db:              <%= ENV['ODH_DB_DB'] %>
  odh_db_user:            <%= ENV['ODH_DB_USER'] %>
  odh_db_pass:            <%= ENV['ODH_DB_PASS'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key:      <%= ENV['STRIPE_SECRET_KEY'] %>
